defmodule SiteWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :site

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_site_key",
    signing_salt: "YwZUx5BV",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, session: @session_options]],
    longpoll: [connect_info: [:peer_data, session: @session_options]]

  # User-uploaded photos. Path is compile-time, defaulting to the dev
  # location under priv/static/uploads. Prod overrides it to the Fly
  # volume mount in config/prod.exs.
  # Must run BEFORE the "/" Plug.Static below so /uploads/* doesn't trip
  # the :only / :raise_on_missing_only check on the priv/static plug.
  plug Plug.Static,
    at: "/uploads",
    from: Application.compile_env(:site, :uploads_dir, {:site, "priv/static/uploads"}),
    gzip: false,
    only: ~w(photos)

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :site,
    gzip: not code_reloading?,
    only: SiteWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :site
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug SiteWeb.Router
end
